site_name: ERPAL Platform Docs
repo_url: https://github.com/brightsolutions/ERPAL-Platform-Docs
site_description: Project documentation for ERPAL Platform

pages:
- [index.md, 'Home']
- [introduction/about_erpal.md, 'Introduction', 'About ERPAL']
- [introduction/about_docs.md, 'Introduction', 'About this documentation']
- [introduction/roles.md, 'Introduction', 'Roles in this documentation']
#- [concepts/index.md, 'Concepts', 'Termdefinitions']
- [concepts/product.md, 'Concepts', 'Product (bundle of entity product)']
- [concepts/line-item.md, 'Concepts', 'Line item']
- [concepts/deliveries.md, 'Concepts', 'Deliveries']
- [concepts/revenue.md, 'Concepts', 'Revenue']
- [concepts/quote.md, 'Concepts', 'Quote']
- [concepts/order.md, 'Concepts', 'Order']
- [concepts/invoice.md, 'Concepts', 'Invoice']
- [concepts/taxes.md, 'Concepts', 'Taxes']
- [concepts/project.md, 'Concepts', 'Project']
- [concepts/budgets.md, 'Concepts', 'Budgets']
- [concepts/audit-proof.md, 'Concepts', 'Audit-proof']
- [usecases/usecases.md, 'Use cases']
- [development/development.md, 'Development', 'Development']

theme: ""
theme_dir: erpaltheme
